---
title: Javier G. Salcedo
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: by Javier G. Salcedo
email: popopojgs@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under
  the Creative Commons.
baseurl: "/blog-jekyll"
url: 
author: Javier G. Salcedo
street_address: 
city: 
state: 
zip_code: 
country: Spain
phone: 
tiles-source: pages
tiles-count: 6
500px_url: 
facebook_url: 
github_url: https://github.com/popopojgs
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/javiergsalcedo/
pinterest_url: 
slack_url: 
twitter_url: 
markdown: kramdown
sass:
  style: compressed
